#!/bin/bash

set -e

echo "Running pre-commit checks"

ROOT_DIR=$(git rev-parse --show-toplevel)
cd "$ROOT_DIR"

deno fmt
deno check ./src
deno task test
deno task readme && git add "$ROOT_DIR/README.md"
